### ISSUE TITLE
assertEqual does not support nullptr

### ISSUE THREAD

**Issue by hlovdal** [ianfixes/arduino_ci#102]
Trying to test that a function returns a null pointer, e.g.

```C++
	assertEqual(nullptr, result);
```

does not work

```shell
.../ArduinoUnitTests.h:69:56: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::nullptr_t’)
               cerr << "      " << lhsRelevance << ": " << lhs << endl;
```

I tried to fix it by extracting that line into a template function and then make a template specialisation for nullptr but did not get the compiler to select it, and have put that on ice for now since there is a simple workaround, just adding
```C++
#define nullptr (void *)NULL
```
at the top of the test file. But it would be nice to eventually have this fixed.

**Comment by ianfixes** [comment]
Yup, this seems like part of C++11 that needs to be added to the mocks.  What's the data type of `result` in the code you posted?  I'll add that to a unit test.

**Comment by ianfixes** [comment]
I will add `nullptr` and `assertNull(result)`

**Comment by hlovdal** [comment]
Those updates still do not fix the issue with `assertEqual`. The problem is that onAssert tries to print the argument of type `nullptr` which it is not able to. There needs to be an additional unit test:

```C++
unittest(nullpointer_equal)
{
  int* myPointer = NULL;
  int **notNullPointer = &myPointer;
  assertEqual(nullptr, myPointer);
  assertNotEqual(nullptr, notNullPointer);

#if 0
  // The following should not compile, which they currently do not but in a
  // cryptic way. If possible and with low effort an explicit denial which
  // produces an explanatory error would be nice.
  assertLessOrEqual(nullptr, myPointer);
  assertMoreOrEqual(nullptr, notNullPointer);
  assertLess(nullptr, myPointer);
  assertMore(nullptr, notNullPointer);
  assertFalse(nullptr);
  assertTrue(nullptr);
  assertAnyLhsRhsFunction(..., nullptr);
#endif
}
```

**Comment by ianfixes** [comment]
Thanks, those unit tests are exactly what was needed.

**Comment by ianfixes** [comment]
@hlovdal You gave me an excellent idea here.

I've set up a new branch called `tdd` (https://github.com/ianfixes/arduino_ci/tree/tdd).  If you can write unit tests that show a problem, make a PR using the `tdd` branch as a base.  That will give me something to work from when I go about fixing the issue.

**Comment by ianfixes** [comment]
This fix is live in the latest version, sorry for the arbitrary delay there
