### ISSUE TITLE
[question] Specify dependency version

### ISSUE THREAD

**Issue by FedeBev** [ianfixes/arduino_ci#142]
Is it possible to specify the version of a library in `.arduino-ci.yaml`? I'm not able to find any example.

Thanks

**Comment by ianfixes** [comment]
Unfortunately there is no way to do this, and that is a reflection of a lack of support for this in the Arduino IDE's library manager.

That said, I tried to design around that limitation by having this project only download libraries that appeared to be missing.  So if your CI script manually downloads the [version of the] library you need, and puts it in the appropriate Arduino library directory, then everything should work as you expect.

I've heard some discussion about versioning coming to the Arduino IDE, but I haven't followed up on it.

Does that work?
