### ISSUE TITLE
Code style test finds 2160 offenses

### ISSUE THREAD

**Issue by jgfoster** [ianfixes/arduino_ci#152]
## System

- OS: macOS Catalina (10.15.6)
- `ruby -v`: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
- `bundle -v`: Bundler version 1.17.2
- `bundle info arduino_ci`:
  arduino_ci (0.3.0)
  Summary: Tools for building and unit testing Arduino libraries
  Homepage: http://github.com/ianfixes/arduino_ci
  Path: /Users/jfoster/code/arduino_ci
- `g++ -v`:
  Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
  Apple clang version 11.0.3 (clang-1103.0.32.62)
  Target: x86_64-apple-darwin19.6.0
  Thread model: posix
  InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- Arduino IDE version: 1.8.13
- `java -version`: 
  java version "11.0.7" 2020-04-14 LTS
  Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
  Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
- URL of failing Travis CI job: N/A
- URL of your Arduino project: https://github.com/Open-Acidification/Open_Acidification_pH-stat_arduino

## Numerous style test problems.

The [Contributing](https://github.com/ianfixes/arduino_ci/blob/master/CONTRIBUTING.md) guidelines say to run `bundle exec rubocop -D .` but when I do so after making a trivial change to one documentation file I get 2160 offenses. Does the CI job actually test this? Should they be fixed or should the contributing instructions be modified? Or is it something I'm doing wrong or misunderstand?

## Arduino or Unit Test Code, Illustrating the Problem

`bundle exec rubocop -D .`

**Comment by ianfixes** [comment]
Rubocop is finding the vendor bundles in the sample projects, which wouldn't happen during CI.  In any case I'll merge #153 when it passes so that you don't experience this in the future.
